navikt/fplos

- .github/dependabot.yml
- pom.xml
- web/src/main/java/no/nav/foreldrepenger/los/web/app/tjenester/felles/dto/OppgaveDtoTjeneste.java
Forsøker skape litt mindre krig om top-3-oppgaver
> Randomiser utvalg av oppgaver

- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/TilbakekrevingHendelseHåndtererTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinnerTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/GjenåpneOppgaveHendelseHåndtererTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/OppgaveTestUtil.java
- pom.xml
- web/src/main/java/no/nav/foreldrepenger/los/web/app/tjenester/abac/ForeldrepengerPipKlient.java
- web/src/main/resources/application.properties
- web/src/test/resources/application-local.properties
> Prosesstask bruker azure når adaptive

- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/FagsakEgenskaper.java
- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinner.java
- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/tilbakekreving/TilbakekrevingOppgaveEgenskapFinner.java
- domene/src/main/java/no/nav/foreldrepenger/los/klient/fpsak/Aksjonspunkt.java
- domene/src/main/java/no/nav/foreldrepenger/los/oppgave/AndreKriterierType.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/TilbakekrevingHendelseHåndtererTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinnerTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/OppgaveTestUtil.java
- pom.xml
> TFP-5457 forenkle og utvide med sammensatt kontroll

- domene/src/main/java/no/nav/foreldrepenger/los/domene/typer/aktør/Person.java
- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/behandlinghendelse/AktørPipKlient.java
- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/Beskyttelsesbehov.java
- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/OppgaveEgenskapHåndterer.java
- domene/src/main/java/no/nav/foreldrepenger/los/klient/person/PersonTjeneste.java
- domene/src/main/java/no/nav/foreldrepenger/los/oppgave/AndreKriterierType.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/OppgaveEgenskapHåndtererTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/TilbakekrevingHendelseHåndtererTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/GenerellOpprettOppgaveHendelseHåndtererTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/GjenåpneOppgaveHendelseHåndtererTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/ReturFraBeslutterHendelseHåndtererTest.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/håndterere/OppdaterOppgaveHendelseHåndtererTest.java
- pom.xml
Har prøvd å få gjennomslag for enklere tilnærming, men venter på svar
> Køkriterie for Kode 7

- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/behandlinghendelse/BehandlingHendelseHåndterer.java
- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/FagsakEgenskaper.java
- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinner.java
- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/tilbakekreving/TilbakekrevingOppgaveEgenskapFinner.java
- domene/src/main/java/no/nav/foreldrepenger/los/klient/fpsak/Aksjonspunkt.java
- domene/src/main/java/no/nav/foreldrepenger/los/oppgave/AndreKriterierType.java
- domene/src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinnerTest.java
- pom.xml
To nye egenskaper basert på fagsakmarkering etter dialog med fagkoordinator
> TFP-1846 egenskaper for dødstilfelle og næring

- domene/src/main/java/no/nav/foreldrepenger/los/organisasjon/ansatt/EnhetstilgangConnection.java
- pom.xml
- web/src/main/resources/application-dev-fss.properties
- web/src/main/resources/application-prod-fss.properties
- web/src/main/resources/application.properties
- web/src/test/resources/application-vtp.properties
> Axsys aad + ny felles

- domene/src/main/java/no/nav/foreldrepenger/los/hendelse/behandlinghendelse/BehandlingHendelseConsumer.java
This reverts commit ea74be4f8afb72f5becd68d2516225ebf6ae2c55.
> Revert "Pushback i lesing av hendelser fra fpsak (#1981)"

- domene/src/main/java/no/nav/foreldrepenger/los/oppgave/OppgaveRepository.java
- domene/src/main/java/no/nav/foreldrepenger/los/statistikk/oppgavebeholdning/StatistikkRepository.java
- web/src/main/java/no/nav/foreldrepenger/los/web/app/tjenester/admin/AdminRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/los/web/app/tjenester/avdelingsleder/nøkkeltall/åpnebehandlinger/FpsakKlient.java
- web/src/main/java/no/nav/foreldrepenger/los/web/app/tjenester/avdelingsleder/nøkkeltall/åpnebehandlinger/FpsakKlientImpl.java
- web/src/main/java/no/nav/foreldrepenger/los/web/app/tjenester/avdelingsleder/nøkkeltall/åpnebehandlinger/NøkkeltallBehandlingerVentestatus.java
- web/src/main/java/no/nav/foreldrepenger/los/web/app/tjenester/avdelingsleder/nøkkeltall/åpnebehandlinger/NøkkeltallÅpneBehandlingerRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/los/web/app/tjenester/avdelingsleder/nøkkeltall/åpnebehandlinger/dto/NøkkeltallBehandlingFørsteUttakDto.java
- web/src/main/java/no/nav/foreldrepenger/los/web/app/tjenester/avdelingsleder/nøkkeltall/åpnebehandlinger/dto/NøkkeltallBehandlingVentefristUtløperDto.java
- web/src/test/java/no/nav/foreldrepenger/los/web/app/tjenester/statistikk/OppgaveBeholdningStatistikkTjenesteTest.java
Endepunkt for å hente ventefristutløp fra fpsak
Grupper første stønadsdag pr uke
Metode for å repopulere revurderinger sin førsteStønadsdato
> TFP-5588 TFP-5589 repopuler revurdering og fristutløp fra sak

- pom.xml
- src/main/java/no/nav/foreldrepenger/los/hendelse/behandlinghendelse/BehandlingHendelseConsumer.java
- src/main/java/no/nav/foreldrepenger/los/hendelse/behandlinghendelse/BehandlingHendelseHåndterer.java
Enkelt oppsett når man bare leser 1 topic. Må skalere til 0 pods før deploy.
Se på fp-oversikt i morgen?
> Falle 708. Kafka Consumer

- pom.xml
- src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinner.java
- src/main/java/no/nav/foreldrepenger/los/organisasjon/ansatt/AnsattTjeneste.java
- src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinnerTest.java
- src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/OppgaveTestUtil.java
> Kontrakt 9 1 15

- src/main/java/no/nav/foreldrepenger/los/organisasjon/ansatt/AnsattTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/organisasjon/ansatt/BrukerProfil.java
- src/main/java/no/nav/foreldrepenger/los/organisasjon/ansatt/LdapBrukeroppslag.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/avdelingsleder/reservasjon/AvdelingReservasjonerRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/ReservasjonStatusDtoTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/SaksbehandlerDto.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/SaksbehandlerDtoTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/SaksbehandlerMedAvdelingerDto.java
- src/test/java/no/nav/foreldrepenger/los/tjenester/avdelingsleder/saksbehandler/AvdelingslederSaksbehandlerRestTjenesteTest.java
Gjenstår en avsjekk med avdelingsledere/Marte før vi kan fjerne avdelingene :)
Valgte å bruke userPrincipalName for epost ettersom jeg ser det er mye i bruk både fra ldap og ms graph api.
> Gjør saksbehandlers epostadresse tilgjengelig for avdelingsleder

- src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinner.java
- src/main/java/no/nav/foreldrepenger/los/oppgave/AndreKriterierType.java
- src/main/java/no/nav/foreldrepenger/los/organisasjon/OrganisasjonRepository.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/admin/AdminRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/admin/dto/DriftOpprettAvdelingEnhetDto.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/kodeverk/KodeverkRestTjeneste.java
Støtte for å opprette avdeling fra AdminRest - behov for 4863
Kriterie for revurdering med kun inntektsmelding - finnes mange av dem
> Opprett enhet og kritering for revurdering/inntektsmelding

- src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/LokalFagsakEgenskap.java
- src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinner.java
- src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/tilbakekreving/TilbakekrevingOppgaveEgenskapFinner.java
Fase 1 - innfører nytt kriterie når klar med populering og saker som skal rehentes
> TFP-5739 TFP-5740 forberede nye egenskaper fra fpsak

- src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinner.java
- src/main/java/no/nav/foreldrepenger/los/oppgave/AndreKriterierType.java
Ikke fagsak-egenskap i denne omgang
> TFP-5740 nytt kriterie for ukjent mor eller mor fra ROW

- src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/Aksjonspunkt.java
- src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinner.java
- src/main/java/no/nav/foreldrepenger/los/oppgave/AndreKriterierType.java
- src/test/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinnerTest.java
Ser på å kjøre en sync etter merging for å på egenskap på beholdning.
> Nytt kriterie KONTROLLER_TERMINBEKREFTELSE 5001 (TFP-5958)

- pom.xml
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/OppgaveDtoTjeneste.java
- src/main/resources/application.properties
- src/test/java/no/nav/foreldrepenger/los/struktur/RestApiAbacTest.java
- src/test/resources/application-vtp.properties
Har lånt litt kode for å sjekke populasjonstilgang - for å sanere abac. Sjekker ikke fagtilgang (antar beslutter i beslutterkø) 
Skal lage en egen PR for å lage utgående filter - trengs også i fpfordel.
> TFP-5952 egen tilgangskontroll

- src/main/java/no/nav/foreldrepenger/los/oppgave/OppgaveRepository.java
- src/main/java/no/nav/foreldrepenger/los/server/abac/ForeldrepengerPipKlient.java
- src/main/java/no/nav/foreldrepenger/los/server/abac/PdpRequestBuilderImpl.java
- src/main/java/no/nav/foreldrepenger/los/statistikk/kø/KøStatistikkRepository.java
- src/main/java/no/nav/foreldrepenger/los/statistikk/kø/SlettUtdatertKoStatistikkTask.java
Forberedelse for endring i felles. Merges etter PR i fpsak
> TFP-5972 innledende omlegging før ny felles

- src/main/java/no/nav/foreldrepenger/los/server/abac/ForeldrepengerPipKlient.java
- src/test/resources/application-vtp.properties
Manglet full path til fpsak pip-tjeneste. Legger til oppsett for lokal utvikling og kjøring i IDE
> Full sti til fpsak pip

- pom.xml
- src/main/java/no/nav/foreldrepenger/los/server/abac/PdpRequestBuilderImpl.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/admin/AdminRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/avdelingsleder/nøkkeltall/NøkkeltallRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/avdelingsleder/nøkkeltall/NøkkeltallÅpneBehandlingerRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/avdelingsleder/reservasjon/AvdelingReservasjonerRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/avdelingsleder/saksbehandler/AvdelingslederSaksbehandlerRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/avdelingsleder/saksliste/AvdelingslederSakslisteRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/OppgaveDtoTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/reservasjon/ReservasjonRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/saksbehandler/enhet/SaksbehandlerEnhetRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/saksbehandler/nøkkeltall/SaksbehandlerNøkkeltallRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/saksbehandler/oppgave/OppgaveRestTjeneste.java
Oppgavelister er utenfor loggbehov
> TFP-5951 tilbasning auditlog

- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/OppgaveDtoTjeneste.java
Sendte alle oppgaver til sjekk - mye overhead og treg respons
> TFP-5972 send kortere liste til fptilgang

- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/OppgaveDtoTjeneste.java
Hold start på oppgavevindu fast gjennom dagen for en gitt saksbehandler.
> chore: Mindre random utvalg av oppgaver

- src/main/java/no/nav/foreldrepenger/los/hendelse/hendelsehåndterer/fpsak/FpsakOppgaveEgenskapFinner.java
- src/main/java/no/nav/foreldrepenger/los/oppgave/AndreKriterierType.java
Prioriterer å ta inn disse pga risk for feilutbetaling (henger litt sammen med berørt og pleiepenger)
> TFP-6253 legger til to behandlingsårsaker med risk for feilutbetaling

- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/OppgaveDto.java
NB, denne må være prodsatt først: https://github.com/navikt/fp-frontend/pull/6458
> chore: contract fase, fjerner ubrukt status-felt

- src/main/java/no/nav/foreldrepenger/los/tjenester/avdelingsleder/saksliste/AvdelingslederSakslisteRestTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/SakslisteDto.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/saksbehandler/saksliste/SaksbehandlerSakslisteRestTjeneste.java
Frontend må inn først: https://github.com/navikt/fp-frontend/pull/6508
> Ytelsesforbedring: fjern antall åpne behandlinger fra SakslisteDto (TFP-6339)

- src/main/java/no/nav/foreldrepenger/los/avdelingsleder/AvdelingslederTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/oppgave/OppgaveRepository.java
- src/main/java/no/nav/foreldrepenger/los/oppgavekø/OppgaveKøTjeneste.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/avdelingsleder/saksliste/dto/SorteringDto.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/AndreKriterierDto.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/SakslisteDto.java
- src/main/java/no/nav/foreldrepenger/los/tjenester/felles/dto/SakslisteIdDto.java
- src/test/java/no/nav/foreldrepenger/los/avdelingsleder/AvdelingslederTjenesteTest.java
- src/test/java/no/nav/foreldrepenger/los/oppgave/OppgaveRepositoryTest.java
Fjerner ubrukt dato i SakslisteDto
Gjør om noen pojo responser til records
> TFP-6339: fjern ubrukt dato i SakslisteDto
